complete -c colorls -s a -l all -d "do not ignore entries starting with ."
complete -c colorls -s A -l almost-all -d "do not list . and .."
complete -c colorls -s l -l long -d "use a long listing format"
complete -c colorls -l tree -d "shows tree view of the directory"
complete -c colorls -l report -d "show brief report"
complete -c colorls -s 1 -d "list one file per line"
complete -c colorls -s d -l dirs -d "show only directories"
complete -c colorls -s f -l files -d "show only files"
complete -c colorls -l gs -l git-status -d "show git status for each file"
complete -c colorls -l sd -l sort-dirs -l group-directories-first -d "sort directories first"
complete -c colorls -l sf -l sort-files -d "sort files first"
complete -c colorls -s t -d "sort by modification time, newest first"
complete -c colorls -s U -d "do not sort; list entries in directory order"
complete -c colorls -s S -d "sort by file size, largest first"
complete -c colorls -l sort -d "sort by WORD instead of name: none, size (-S), time (-t) -x -a none time size"
complete -c colorls -s r -l reverse -d "reverse order while sorting"
complete -c colorls -l light -d "use light color scheme"
complete -c colorls -l dark -d "use dark color scheme"
complete -c colorls -s h -l help -d "prints this help"
complete -c colorls -l version -d "show version"
